name: example
description: "example for set_state_async"
publish_to: "none"
environment:
  sdk: ">=3.0.0"
  flutter: ">=3.0.0"
dependencies:
  flutter:
    sdk: flutter
  inview_notifier_list: any
  set_state_async:
    path: ../

dev_dependencies:
  flutter_lints: any

flutter:
  uses-material-design: true