name: set_state_async
description: "A mixin for avoiding State.setState during build or locking issue and improving performance."
version: 0.1.2
repository: "https://github.com/xxoo/set_state_async"
issue_tracker: "https://github.com/xxoo/set_state_async/issues"
topics:
  - set-state
  - async
  - state
  - performance
  - optimization

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: any