name: set_state_async
description: 'A mixin to avoid "setState while building or locked" issue and improve performance.'
version: 0.1.8
repository: 'https://github.com/xxoo/set_state_async'
issue_tracker: 'https://github.com/xxoo/set_state_async/issues'
topics:
  - set-state
  - async
  - workaround
  - tweak
  - performance

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: any